In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings 
warnings.filterwarnings('ignore')

df=pd.read_csv('student_data_100000.csv')

In [2]:
df.head()

,attendance,study_hours,past_failures,assignments_completed_pct,parental_education,family_income,extracurricular,internet_access,previous_grade,final_score,risk_category
0,87.42,10.12,2,100.00,Secondary,Low,Yes,Yes,46.80,76.08,Safe
1,71.54,1.38,3,36.70,Secondary,High,Yes,Yes,48.05,43.21,High-Risk
2,91.19,8.30,5,64.38,Secondary,Low,No,Yes,69.40,60.89,At-Risk
3,100.00,3.52,4,93.77,Secondary,Low,No,No,58.07,45.47,At-Risk
4,69.15,4.69,1,72.36,Primary,Low,Yes,Yes,50.55,37.15,High-Risk

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   attendance                 99000 non-null   float64
 1   study_hours                99000 non-null   float64
 2   past_failures              100000 non-null  int64
 3   assignments_completed_pct  100000 non-null  float64
 4   parental_education         100000 non-null  str
 5   family_income              100000 non-null  str
 6   extracurricular            100000 non-null  str
 7   internet_access            100000 non-null  str
 8   previous_grade             100000 non-null  float64
 9   final_score                100000 non-null  float64
 10  risk_category              100000 non-null  str
dtypes: float64(5), int64(1), str(5)
memory usage: 10.7 MB

In [35]:
df1['attendance']=df['attendance'].fillna(df['attendance'].mean())

In [36]:
df1['study_hours']=df['study_hours'].fillna(df['study_hours'].mean())

In [37]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   attendance                 100000 non-null  float64
 1   study_hours                100000 non-null  float64
 2   past_failures              100000 non-null  int64
 3   assignments_completed_pct  100000 non-null  float64
 4   parental_education         100000 non-null  str
 5   family_income              100000 non-null  str
 6   extracurricular            100000 non-null  str
 7   internet_access            100000 non-null  str
 8   previous_grade             100000 non-null  float64
 9   final_score                100000 non-null  float64
 10  risk_category              100000 non-null  str
dtypes: float64(5), int64(1), str(5)
memory usage: 10.7 MB

In [7]:
cols=df.columns

In [8]:
cols=['parental_education', 'family_income','risk_category']
for i in cols:
    print(df[i].unique())

<ArrowStringArray>
['Secondary', 'Primary', 'Higher', 'none']
Length: 4, dtype: str
<ArrowStringArray>
['Low', 'High', 'Medium']
Length: 3, dtype: str
<ArrowStringArray>
['Safe', 'High-Risk', 'At-Risk']
Length: 3, dtype: str

In [38]:
df1['extracurricular']=df1['extracurricular'].map({'Yes':1,'No':0})
df1['internet_access']=df1['internet_access'].map({'Yes':1,'No':0})
df1['parental_education']=df1['parental_education'].map({'Secondary':2, 'Primary':1, 'Higher':3, 'none':0})
df1['family_income']=df1['family_income'].map({'Low':0, 'High':2, 'Medium':1})
df1['risk_category']=df1['risk_category'].map({'Safe':0, 'High-Risk':2, 'At-Risk':1})

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
scaler=StandardScaler()

In [12]:
df.head()

,attendance,study_hours,past_failures,assignments_completed_pct,parental_education,family_income,extracurricular,internet_access,previous_grade,final_score,risk_category
0,87.42,10.12,2,100.00,2,0,1,1,46.80,76.08,0
1,71.54,1.38,3,36.70,2,2,1,1,48.05,43.21,2
2,91.19,8.30,5,64.38,2,0,0,1,69.40,60.89,1
3,100.00,3.52,4,93.77,2,0,0,0,58.07,45.47,1
4,69.15,4.69,1,72.36,1,0,1,1,50.55,37.15,2

In [41]:
num_cols=['attendance', 'study_hours', 'past_failures',
       'assignments_completed_pct','previous_grade']

In [42]:
df1[num_cols]=scaler.fit_transform(df1[num_cols])

In [15]:
df.head()

,attendance,study_hours,past_failures,assignments_completed_pct,parental_education,family_income,extracurricular,internet_access,previous_grade,final_score,risk_category
0,0.673397,1.084848,0.101489,1.250010,2,0,1,1,-1.210085,0.825251,0
1,-0.066772,-1.274868,0.772050,-1.672949,2,2,1,1,-1.152279,-1.243579,2
2,0.849118,0.593466,2.113172,-0.394790,2,0,0,1,-0.164957,-0.130804,1
3,1.259753,-0.697089,1.442611,0.962332,2,0,0,0,-0.688908,-1.101335,1
4,-0.178171,-0.381200,-0.569071,-0.026303,1,0,1,1,-1.036668,-1.624994,2

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report

In [17]:
X=df.drop('risk_category',axis=1)
y=df['risk_category']

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [19]:
model1=LogisticRegression()
model1.fit(X_train,y_train)

LogisticRegression()

In [20]:
model2=SVC(random_state=42)
model3=DecisionTreeClassifier()
model2.fit(X_train,y_train)
model3.fit(X_train,y_train)

DecisionTreeClassifier()

In [21]:
y_pred1=model1.predict(X_test)
y_pred2=model2.predict(X_test)
y_pred3=model3.predict(X_test)

In [22]:
acc_list=[]

In [23]:
acc_list.append(accuracy_score(y_test,y_pred3))

In [24]:
acc_list

[0.85975]

In [25]:
print(classification_report(y_test,y_pred1))
print(classification_report(y_test,y_pred2))
print(classification_report(y_test,y_pred3))

              precision    recall  f1-score   support

           0       0.94      0.93      0.93      4982
           1       0.93      0.94      0.94      9914
           2       0.95      0.93      0.94      5104

    accuracy                           0.94     20000
   macro avg       0.94      0.94      0.94     20000
weighted avg       0.94      0.94      0.94     20000

              precision    recall  f1-score   support

           0       0.94      0.93      0.93      4982
           1       0.93      0.95      0.94      9914
           2       0.95      0.93      0.94      5104

    accuracy                           0.94     20000
   macro avg       0.94      0.93      0.94     20000
weighted avg       0.94      0.94      0.94     20000

              precision    recall  f1-score   support

           0       0.86      0.86      0.86      4982
           1       0.86      0.86      0.86      9914
           2       0.87      0.86      0.86      5104

    accuracy                           0.86     20000
   macro avg       0.86      0.86      0.86     20000
weighted avg       0.86      0.86      0.86     20000

In [26]:
df1=pd.read_csv('student_data_100000.csv')

In [27]:
df1['risk_category'].value_counts()

risk_category
At-Risk      49990
Safe         25011
High-Risk    24999
Name: count, dtype: int64

In [28]:
import joblib
joblib.dump(model1,'LR_Student.pkl')
joblib.dump(scaler,'scaler.pkl')
joblib.dump(X.columns.to_list(),'columns.pkl')

['columns.pkl']

In [29]:
X.columns

Index(['attendance', 'study_hours', 'past_failures',
       'assignments_completed_pct', 'parental_education', 'family_income',
       'extracurricular', 'internet_access', 'previous_grade', 'final_score'],
      dtype='str')

In [30]:
X.describe

<bound method NDFrame.describe of        attendance  study_hours  past_failures  assignments_completed_pct  \
0        0.673397     1.084848       0.101489                   1.250010
1       -0.066772    -1.274868       0.772050                  -1.672949
2        0.849118     0.593466       2.113172                  -0.394790
3        1.259753    -0.697089       1.442611                   0.962332
4       -0.178171    -0.381200      -0.569071                  -0.026303
...           ...          ...            ...                        ...
99995   -0.167916    -1.393664      -0.569071                  -0.904114
99996   -0.569230     0.582666       0.101489                  -0.364313
99997    0.571321     0.145282      -0.569071                  -1.263365
99998   -0.151603     0.895855       0.772050                  -1.322933
99999    0.234330    -1.177672       2.113172                  -0.858861

       parental_education  family_income  extracurricular  internet_access  \
0                       2              0                1                1
1                       2              2                1                1
2                       2              0                0                1
3                       2              0                0                0
4                       1              0                1                1
...                   ...            ...              ...              ...
99995                   3              1                0                1
99996                   1              0                1                1
99997                   2              1                0                1
99998                   2              0                0                1
99999                   3              2                1                1

       previous_grade  final_score
0           -1.210085     0.825251
1           -1.152279    -1.243579
2           -0.164957    -0.130804
3           -0.688908    -1.101335
4           -1.036668    -1.624994
...               ...          ...
99995        1.250126    -0.067864
99996        1.250126     1.758648
99997       -1.515761    -0.356757
99998        0.951849    -0.721808
99999       -1.490327    -1.375123

[100000 rows x 10 columns]>

In [33]:
df1.head()

,attendance,study_hours,past_failures,assignments_completed_pct,parental_education,family_income,extracurricular,internet_access,previous_grade,final_score,risk_category
0,87.42,10.12,2,100.00,Secondary,Low,Yes,Yes,46.80,76.08,Safe
1,71.54,1.38,3,36.70,Secondary,High,Yes,Yes,48.05,43.21,High-Risk
2,91.19,8.30,5,64.38,Secondary,Low,No,Yes,69.40,60.89,At-Risk
3,100.00,3.52,4,93.77,Secondary,Low,No,No,58.07,45.47,At-Risk
4,69.15,4.69,1,72.36,Primary,Low,Yes,Yes,50.55,37.15,High-Risk

In [43]:
df1.describe()

,attendance,study_hours,past_failures,assignments_completed_pct,parental_education,family_income,extracurricular,internet_access,previous_grade,final_score,risk_category
count,1.000000e+05,1.000000e+05,1.000000e+05,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.000000,1.000000e+05,100000.000000,100000.000000
mean,3.240075e-17,2.742695e-17,5.741185e-17,1.753619e-16,1.901490,0.698440,0.500070,0.898860,-2.198419e-16,62.968236,0.999880
std,1.000005e+00,1.000005e+00,1.000005e+00,1.000005e+00,0.886078,0.780569,0.500002,0.301516,1.000005e+00,15.888285,0.707181
min,-2.935163e+00,-1.647455e+00,-1.239632e+00,-3.367619e+00,0.000000,0.000000,0.000000,0.000000,-3.374331e+00,0.000000,0.000000
25%,-6.810943e-01,-7.456870e-01,-5.690714e-01,-6.852383e-01,2.000000,0.000000,0.000000,1.000000,-6.833591e-01,52.220000,0.000000
50%,8.238038e-02,-1.401283e-02,1.014894e-01,9.883498e-02,2.000000,0.000000,1.000000,1.000000,9.586187e-02,63.160000,1.000000
75%,8.747534e-01,6.906623e-01,7.720502e-01,8.727495e-01,2.000000,1.000000,1.000000,1.000000,8.750828e-01,73.990000,1.000000
max,1.259753e+00,2.402402e+00,2.113172e+00,1.250010e+00,3.000000,2.000000,1.000000,1.000000,1.250126e+00,100.000000,2.000000

In [45]:
df1.head()

,attendance,study_hours,past_failures,assignments_completed_pct,parental_education,family_income,extracurricular,internet_access,previous_grade,final_score,risk_category
0,0.673397,1.084848,0.101489,1.250010,2,0,1,1,-1.210085,76.08,0
1,-0.066772,-1.274868,0.772050,-1.672949,2,2,1,1,-1.152279,43.21,2
2,0.849118,0.593466,2.113172,-0.394790,2,0,0,1,-0.164957,60.89,1
3,1.259753,-0.697089,1.442611,0.962332,2,0,0,0,-0.688908,45.47,1
4,-0.178171,-0.381200,-0.569071,-0.026303,1,0,1,1,-1.036668,37.15,2